name: in_shorts_movies
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^16.2.4
  provider: ^6.1.5+1
  loader_overlay: ^5.0.0
  shared_preferences: ^2.5.3
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.6
  connectivity_plus: ^7.0.0
  retrofit: ^4.7.3
  dio: ^5.9.0
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  carousel_slider: ^5.0.0
  cached_network_image: ^3.4.1
  share_plus: ^10.0.2
  gap: ^3.0.1
  flutter_staggered_animations: ^1.1.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  intl_utils: ^2.8.9
  build_runner: ^2.4.12
  logger: ^2.6.1
  retrofit_generator: ^10.0.6

  # flutter pub run intl_utils:generate
flutter_intl:
  enabled: true
  class_name: S # Optional. Sets the name for the generated localization class. Default: S
  main_locale: en # Optional. Sets the main locale used for generating localization files. Provided value should consist of language code and optional script and country codes separated with underscore (e.g. 'en', 'en_GB', 'zh_Hans', 'zh_Hans_CN'). Default: en
  arb_dir: lib/core/l10n # Optional. Sets the directory of your ARB resource files. Provided value should be a valid path on your system. Default: lib/l10n
  output_dir: lib/core/l10n/generated

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/

  # An images asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/static/Roboto-Thin.ttf
          weight: 100
        - asset: assets/fonts/Roboto/static/Roboto-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Roboto/static/Roboto-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Roboto/static/Roboto-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Roboto/static/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto/static/Roboto-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Roboto/static/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto/static/Roboto-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Roboto/static/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto/static/Roboto-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Roboto/static/Roboto-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Roboto/static/Roboto-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Roboto/static/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto/static/Roboto-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Roboto/static/Roboto-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Roboto/static/Roboto-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Roboto/static/Roboto-Black.ttf
          weight: 900
        - asset: assets/fonts/Roboto/static/Roboto-BlackItalic.ttf
          weight: 900
          style: italic

# dart run flutter_native_splash:create
flutter_native_splash:
  android: true
  ios: true
  web: false

  color: "#FFFFFF"
#  image: assets/images/splash_logo.png


  android_12:
    fullscreen: true
    color: "#FFFFFF"
#    branding: assets/images/splash.png
#    image: assets/images/splash_logo.png
#    icon_background_color: "transparent"
